### ISSUE TITLE
Getting different first result for SWS in different browsers

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#80] opened 2020-08-12 16:08 UTC
### Issue description
*Description of the issue*

Getting different first result while performing search with the same term in different browsers on ODE 377. Chrome and FF returns same first result while IE and Edge returns same first result.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Perform search with "mantle cell lymhoma" on Chrome 
2. Go to page 13
3. Perform search with "mantle cell lymhoma" on Edge
4. Go to page 13
5. Compare the first result in the search results page on both browsers 
6. Repeat step 1-4 in FF and IE
7.  Compare the first result in the search results page on all 4 browsers 

### What's the expected result?
- Edge , IE, Chrome and FF  should return same first search result on page 13. 

### What's the actual result?
- Edge and IE shows same first result on page 13 and Chrome and FF  shows same first result on page 13 

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/90039412-961d6200-dc94-11ea-92e6-3db1b7082f71.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by alinai** [comment] 2020-08-17 19:29
The issue exists on Prod too!

**Comment by sarinapadilla** [comment] 2023-04-04 18:23
I'm unable to reproduce this issue - it has been over two years, and our content has changed a lot since this was first reported. Closing this ticket for now and we can create a new one if the issue comes up again.

**Closed by sarinapadilla** 2023-04-04 18:23 UTC
Labels: bug
