### ISSUE TITLE
Searching for '/' returns error page.

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#75] opened 2020-08-11 20:43 UTC
### Issue description
*Description of the issue*
Searching for '/' returns error page.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Perform SWS with '/'

### What's the expected result?
- user should receive the 'no results' page

### What's the actual result?
- Returns error page

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/89947005-ceb82f80-dbf1-11ea-83b6-9ee0d3ba2387.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blairlearn** [comment] 2020-08-11 21:24
The root cause is that the best bets API fails when `/` is specified as the search term.  See NCIOCPL/bestbets-api#34.

That being said, a best bets failure shouldn't cause the entire search app to fail; though I don't know what the priority is.

**Comment by sarinapadilla** [comment] 2022-08-18 18:07
This issue has been fixed on Prod, so closing this ticket.

**Closed by sarinapadilla** 2022-08-18 18:07 UTC
Labels: bug
